### Import Dependencies

In [11]:
import pandas as pd
from pathlib import Path

### Get File Paths

In [23]:
BASE_DIR = Path.cwd().parent
PLANET_PATH = BASE_DIR / 'data' / 'raw' / 'raw_planet_data.csv'
STAR_PATH = BASE_DIR / 'data' / 'raw' / 'raw_star_data.csv'

### Load Data

In [26]:
planet_data = pd.read_csv(PLANET_PATH)
star_data = pd.read_csv(STAR_PATH)

### Preview Data

In [29]:
planet_data.head()

,planet_name,star_name,planets_in_system,orbital_period,semi_major_axis,radius_earths,mass_earths,radius_jupiters,mass_jupiters,density,equilibrium_temperature,eccentricity,ra,dec
0,HD 80653 b,HD 80653,2,0.719579,0.01657,1.621000,5.610000,0.144616,0.017651,7.24,2438.00,0.0000,140.339085,14.367869
1,K2-312 c,HD 80653,2,871.320000,1.88200,12.800000,1681.312273,1.140000,5.290000,4.41,229.00,0.8435,140.339085,14.367869
2,XO-2 S d,XO-2 S,4,4696.000000,5.46000,13.000000,1179.143390,1.160000,3.710000,2.95,110.98,0.0910,117.030975,50.216907
3,Kepler-1808 b,Kepler-1808,1,23.340401,0.14670,3.025113,9.400000,0.269883,0.029600,1.87,601.00,0.0000,287.292474,39.383204
4,Kepler-418 b,Kepler-418,2,86.678560,0.39249,13.450000,349.611248,1.200000,1.100000,NaN,434.00,0.2000,294.433523,38.355473

In [31]:
star_data.head()

,star_name,star_type,star_temperature,star_radius,star_mass,star_metallicity,star_surface_gravity,star_age
0,HD 80653,G0 V,5959.0,1.199,1.150,0.255,4.342,3.3
1,HD 80653,G0 V,5959.0,1.199,1.150,0.255,4.342,3.3
2,XO-2 S,G8 V,5325.0,1.020,0.980,0.320,4.420,7.1
3,Kepler-1808,NaN,5530.0,0.892,0.773,-0.340,4.425,12.1
4,Kepler-418,NaN,5820.0,1.090,0.980,-0.050,4.350,7.0

In [33]:
planet_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6336 entries, 0 to 6335
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   planet_name              6336 non-null   object
 1   star_name                6336 non-null   object
 2   planets_in_system        6336 non-null   int64
 3   orbital_period           5992 non-null   float64
 4   semi_major_axis          5908 non-null   float64
 5   radius_earths            6286 non-null   float64
 6   mass_earths              6305 non-null   float64
 7   radius_jupiters          6286 non-null   float64
 8   mass_jupiters            6305 non-null   float64
 9   density                  6195 non-null   float64
 10  equilibrium_temperature  5810 non-null   float64
 11  eccentricity             5283 non-null   float64
 12  ra                       6336 non-null   float64
 13  dec                      6336 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 693.1+ KB

In [35]:
star_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6336 entries, 0 to 6335
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   star_name             6336 non-null   object
 1   star_type             2350 non-null   object
 2   star_temperature      6039 non-null   float64
 3   star_radius           6015 non-null   float64
 4   star_mass             6327 non-null   float64
 5   star_metallicity      5694 non-null   float64
 6   star_surface_gravity  6011 non-null   float64
 7   star_age              4897 non-null   float64
dtypes: float64(6), object(2)
memory usage: 396.1+ KB

In [39]:
planet_data.describe()

,planets_in_system,orbital_period,semi_major_axis,radius_earths,mass_earths,radius_jupiters,mass_jupiters,density,equilibrium_temperature,eccentricity,ra,dec
count,6336.000000,5.992000e+03,5908.000000,6286.000000,6305.000000,6286.000000,6305.000000,6195.000000,5810.000000,5283.000000,6336.000000,6336.000000
mean,1.759785,7.144464e+04,15.545361,5.851832,404.433376,0.522098,1.272625,4.842763,834.896141,0.079915,230.713841,17.549925
std,1.150985,5.195691e+06,346.853588,5.422517,1139.778017,0.483807,3.586520,34.047999,496.619821,0.153173,92.611489,37.658890
min,1.000000,9.070629e-02,0.004400,0.309800,0.020000,0.027639,0.000063,0.005100,1.480000,0.000000,0.185606,-89.471513
25%,1.000000,4.308908e+00,0.052300,1.850000,4.310000,0.165000,0.013600,1.270000,485.895000,0.000000,168.226736,-12.525095
50%,1.000000,1.074551e+01,0.102750,2.860000,9.320000,0.255152,0.029300,2.520000,755.625000,0.000000,284.335606,38.947263
75%,2.000000,3.856275e+01,0.311250,11.915990,189.425731,1.068500,0.596000,4.540000,1092.750000,0.092000,293.086590,45.417147
max,8.000000,4.020000e+08,19000.000000,87.205870,9534.852210,7.780000,30.000000,2000.000000,7777.780000,0.950000,359.974984,88.829876

In [41]:
star_data.describe()

,star_temperature,star_radius,star_mass,star_metallicity,star_surface_gravity,star_age
count,6039.000000,6015.000000,6327.000000,5694.000000,6011.000000,4897.000000
mean,5394.344078,1.489258,0.934775,0.016912,4.384416,4.377047
std,1727.761286,3.864738,0.387024,0.188234,0.437646,2.999130
min,415.000000,0.011500,0.009400,-1.000000,0.541000,0.000000
25%,4898.500000,0.770000,0.770000,-0.080000,4.292000,2.300000
50%,5544.000000,0.950000,0.940000,0.020000,4.454000,3.980000
75%,5899.500000,1.249295,1.087500,0.130000,4.580000,5.700000
max,57000.000000,88.475000,9.100000,0.790000,8.070000,16.100000